CREATE DATABASE UNPAZ;

USE UNPAZ;

CREATE TABLE Alumno
(
	Legajo INT,
	DNI INT NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Genero VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Alumno PRIMARY KEY(Legajo),
	CONSTRAINT U_DNI UNIQUE(DNI)
);

CREATE TABLE Materia
(
	ID INT,
	Descripcion VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Materia PRIMARY KEY(ID),
	CONSTRAINT U_Descripcion UNIQUE(Descripcion)
);

CREATE TABLE Final
(
	ID_Materia INT,
	Legajo_Alumno INT,
	Fecha DATE,
	Nota NUMERIC(4, 2) NOT NULL,
	CONSTRAINT PK_Final PRIMARY KEY(ID_Materia, Legajo_Alumno, Fecha),
	CONSTRAINT FK_Materia FOREIGN KEY (ID_Materia) REFERENCES Materia(ID) ON DELETE CASCADE,
	CONSTRAINT FK_Alumno FOREIGN KEY(Legajo_Alumno) REFERENCES Alumno(Legajo) ON DELETE CASCADE,
	CONSTRAINT CK_Fecha CHECK(Fecha <= getdate()),
	CONSTRAINT CK_Nota CHECK(Nota > 0 AND Nota <= 10)
);